# Generated by Django 3.1.7 on 2021-04-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.PositiveIntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('train_from', models.CharField(max_length=100)),
                ('train_to', models.CharField(max_length=70)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('train_price', models.PositiveIntegerField()),
                ('train_category', models.CharField(choices=[('1AC', 'Air-conditioned First class'), ('2AC', 'Air conditioned 2-tier'), ('3AC', 'Air conditioned 3-tier'), ('CC', 'AC- Chair Class'), ('SL', 'Sleeper Class')], max_length=70)),
                ('running_days', models.CharField(max_length=70)),
                ('time_taken', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
