# Generated by Django 3.1.7 on 2021-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seat_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
