# Generated by Django 3.1.7 on 2021-04-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_train_seat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='seat_no',
        ),
    ]
